name: dauys_remote
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  flutter_svg: ^2.0.14
  blur: ^4.0.0
  smooth_page_indicator: ^1.2.0+3
  intl: ^0.19.0
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2
  stomp_dart_client: ^2.1.0
  flutter_phoenix: ^1.1.1
  flutter_i18n: ^0.36.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/icons/
    - assets/tmp/
    - assets/i18n/

  fonts:
    - family: Magistral
      fonts:
        - asset: assets/fonts/Magistral/Magistral-Bold.ttf
          weight: 700
        - asset: assets/fonts/Magistral/Magistral-Bold.ttf
          weight: 600
        - asset: assets/fonts/Magistral/Magistral-Bold.ttf
          weight: 500
        - asset: assets/fonts/Magistral/Magistral-Medium.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Magistral/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Magistral/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Magistral/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Magistral/Roboto-Light.ttf
          weight: 400
