// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPAmTdFG9D_gHykGWorRKnw2Bg5D_j4AQ',
    appId: '1:966936741628:android:96154b04bd5e18935fb979',
    messagingSenderId: '966936741628',
    projectId: 'novo-team',
    databaseURL: 'https://novo-team.firebaseio.com',
    storageBucket: 'novo-team.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOm8NUj9cjK9Ca2UinLvXS4_8U0U-F2b0',
    appId: '1:966936741628:ios:d471996b30e77f6b5fb979',
    messagingSenderId: '966936741628',
    projectId: 'novo-team',
    databaseURL: 'https://novo-team.firebaseio.com',
    storageBucket: 'novo-team.firebasestorage.app',
    androidClientId: '966936741628-2if18s35iqvtbh3g5t1ie9n5qpvnk7c4.apps.googleusercontent.com',
    iosClientId: '966936741628-en7ho85et0ovu2eia6ek96el8h8gg92t.apps.googleusercontent.com',
    iosBundleId: 'com.example.dauysRemote',
  );
}
